"""A tiny, schema-driven protobuf (proto3) implementation.

WhatsApp encodes every payload as protobuf.  Instead of pulling in the
``protobuf`` runtime we implement the wire format here and drive it with the
field tables generated by ``tools/gen_proto.py`` into
``xbot/wa/protoschema.py``.

Usage::

    from xbot.wa import protobuf as pb
    data = pb.encode("SignalMessage", {"ratchetKey": key, "counter": 3, "ciphertext": ct})
    parsed = pb.decode("SignalMessage", data)
"""

from __future__ import annotations

import struct
from typing import Any, Dict, List, Optional, Tuple

from .protoschema import ENUMS, MESSAGES

# --------------------------------------------------------------------------
# Schema resolution
# --------------------------------------------------------------------------

_resolve_cache: Dict[Tuple[str, str], Optional[str]] = {}


def resolve_type(parent: str, target: str) -> Optional[str]:
    """Resolve a (possibly short) type name against the enclosing scope."""
    key = (parent, target)
    if key in _resolve_cache:
        return _resolve_cache[key]
    # protobuf scoping: the innermost enclosing scope wins, then the root
    result = None
    parts = parent.split(".")
    for i in range(len(parts), 0, -1):
        candidate = ".".join(parts[:i]) + "." + target
        if candidate in MESSAGES or candidate in ENUMS:
            result = candidate
            break
    if result is None and (target in MESSAGES or target in ENUMS):
        result = target
    _resolve_cache[key] = result
    return result


def _field_kinds(message: str):
    """Yield ``(name, number, label, kind, target, packed, target_kind)``."""
    fields = MESSAGES.get(message)
    if fields is None:
        raise KeyError(f"unknown protobuf message {message!r}")
    for name, number, label, kind, target, packed in fields:
        if kind == "msg":
            resolved = resolve_type(message, target) if target else None
            if resolved and resolved in ENUMS:
                yield name, number, label, "enum", resolved, packed
            else:
                yield name, number, label, "msg", resolved or target, packed
        else:
            yield name, number, label, kind, None, packed


def _by_number(message: str) -> Dict[int, tuple]:
    return {f[1]: f for f in _field_kinds(message)}


_SCHEMA_BY_NUM: Dict[str, Dict[int, tuple]] = {}


def schema_by_number(message: str) -> Dict[int, tuple]:
    if message not in _SCHEMA_BY_NUM:
        _SCHEMA_BY_NUM[message] = _by_number(message)
    return _SCHEMA_BY_NUM[message]


# --------------------------------------------------------------------------
# Varint helpers
# --------------------------------------------------------------------------


def _write_varint(out: bytearray, value: int) -> None:
    if value < 0:
        value &= (1 << 64) - 1
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return


def _read_varint(data: bytes, pos: int) -> Tuple[int, int]:
    result = 0
    shift = 0
    while True:
        if pos >= len(data):
            raise ValueError("truncated varint")
        byte = data[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if not byte & 0x80:
            return result, pos
        shift += 7
        if shift > 70:
            raise ValueError("varint too long")


def _zigzag_encode(value: int) -> int:
    return (value << 1) ^ (value >> 63)


def _zigzag_decode(value: int) -> int:
    return (value >> 1) ^ -(value & 1)


# --------------------------------------------------------------------------
# Encoding
# --------------------------------------------------------------------------


def _encode_value(out: bytearray, kind: str, value: Any) -> None:
    if kind in ("int", "enum", "bool"):
        if kind == "bool":
            value = 1 if value else 0
        _write_varint(out, int(value))
    elif kind == "sint":
        _write_varint(out, _zigzag_encode(int(value)))
    elif kind in ("fixed64", "double"):
        if kind == "double":
            out += struct.pack("<d", float(value))
        else:
            out += struct.pack("<Q", int(value) & ((1 << 64) - 1))
    elif kind in ("fixed32", "float"):
        if kind == "float":
            out += struct.pack("<f", float(value))
        else:
            out += struct.pack("<I", int(value) & 0xFFFFFFFF)
    else:
        raise ValueError(f"not a scalar kind: {kind}")


def encode_field(out: bytearray, message: str, name: str, value: Any) -> None:
    for f in _field_kinds(message):
        if f[0] == name:
            _encode_one(out, message, f, value)
            return
    raise KeyError(f"{message} has no field {name!r}")


def _encode_one(out: bytearray, message: str, field: tuple, value: Any) -> None:
    name, number, label, kind, target, packed = field
    if value is None:
        return
    if label == "repeated":
        values = list(value)
        if not values:
            return
        if kind in ("msg", "str", "bytes"):
            for item in values:
                _encode_single(out, message, number, kind, target, item)
        elif packed:
            buf = bytearray()
            for item in values:
                _encode_value(buf, kind, item)
            _write_varint(out, (number << 3) | 2)
            _write_varint(out, len(buf))
            out += buf
        else:
            for item in values:
                _encode_single(out, message, number, kind, target, item)
        return
    _encode_single(out, message, number, kind, target, value)


def _encode_single(out: bytearray, message: str, number: int, kind: str,
                   target: Optional[str], value: Any) -> None:
    if kind == "msg":
        if not isinstance(value, dict):
            raise TypeError(f"field {number} expects a dict for message {target}")
        body = bytearray()
        _encode_into(body, target, value)
        _write_varint(out, (number << 3) | 2)
        _write_varint(out, len(body))
        out += body
    elif kind in ("str", "bytes"):
        if kind == "str":
            raw = value.encode("utf-8") if isinstance(value, str) else bytes(value)
        else:
            raw = value if isinstance(value, (bytes, bytearray)) else str(value).encode()
        _write_varint(out, (number << 3) | 2)
        _write_varint(out, len(raw))
        out += raw
    elif kind == "enum":
        if isinstance(value, str):
            values = ENUMS.get(target or "", {})
            if value not in values:
                raise KeyError(f"unknown enum value {target}.{value}")
            value = values[value]
        _write_varint(out, (number << 3) | 0)
        _write_varint(out, int(value))
    else:
        wire = 0 if kind in ("int", "bool", "sint") else (1 if kind in ("fixed64", "double") else 5)
        _write_varint(out, (number << 3) | wire)
        _encode_value(out, kind, value)


def _encode_into(out: bytearray, message: str, obj: dict) -> None:
    known = {f[0]: f for f in _field_kinds(message)}
    for name, value in obj.items():
        field = known.get(name)
        if field is None:
            raise KeyError(f"{message} has no field {name!r}")
        _encode_one(out, message, field, value)


def encode(message: str, obj: dict) -> bytes:
    out = bytearray()
    _encode_into(out, message, obj or {})
    return bytes(out)


def encode_and_len(message: str, obj: dict) -> bytes:
    body = encode(message, obj)
    out = bytearray()
    _write_varint(out, len(body))
    return bytes(out) + body


# --------------------------------------------------------------------------
# Decoding
# --------------------------------------------------------------------------


def _decode_value(kind: str, raw) -> Any:
    if kind == "bool":
        return bool(raw)
    if kind == "sint":
        return _zigzag_decode(raw)
    if kind == "double":
        return struct.unpack("<d", raw)[0]
    if kind == "float":
        return struct.unpack("<f", raw)[0]
    if kind in ("fixed64", "fixed32"):
        return raw
    return raw


def decode(message: str, data: bytes) -> dict:
    return _decode_into(message, bytes(data))


def _decode_into(message: str, data: bytes) -> dict:
    schema = schema_by_number(message)
    out: Dict[str, Any] = {}
    pos = 0
    length = len(data)
    while pos < length:
        key, pos = _read_varint(data, pos)
        number = key >> 3
        wire = key & 7
        field = schema.get(number)
        if wire == 0:
            value, pos = _read_varint(data, pos)
        elif wire == 1:
            value = data[pos:pos + 8]
            pos += 8
        elif wire == 2:
            size, pos = _read_varint(data, pos)
            value = data[pos:pos + size]
            pos += size
        elif wire == 5:
            value = data[pos:pos + 4]
            pos += 4
        else:
            raise ValueError(f"unsupported wire type {wire} in {message}")
        if field is None:
            continue  # unknown field: tolerate and skip
        name, _num, label, kind, target, _packed = field
        if kind == "msg":
            decoded = _decode_into(target, value) if isinstance(value, (bytes, bytearray)) else value
        elif kind == "str":
            decoded = value.decode("utf-8", "replace") if isinstance(value, (bytes, bytearray)) else value
        elif kind == "bytes":
            decoded = bytes(value) if isinstance(value, (bytes, bytearray)) else value
        else:
            decoded = _decode_value(kind, value)
        if label == "repeated":
            out.setdefault(name, []).append(decoded)
        else:
            out[name] = decoded
    return out


# --------------------------------------------------------------------------
# Helpers for the rest of the bot
# --------------------------------------------------------------------------


def enum_name(enum: str, value: int) -> Optional[str]:
    return {v: k for k, v in ENUMS.get(enum, {}).items()}.get(value)


def enum_value(enum: str, name: str) -> Optional[int]:
    return ENUMS.get(enum, {}).get(name)


def has_message(name: str) -> bool:
    return name in MESSAGES


def fields_of(name: str) -> List[tuple]:
    return list(_field_kinds(name))


__all__ = [
    "encode", "decode", "encode_field", "encode_and_len", "resolve_type",
    "fields_of", "enum_name", "enum_value", "has_message",
]
