#!/usr/bin/env python3
"""Regenerate ``xbot/wa/tokens.py`` from Baileys' ``WABinary/constants.ts``.

The token dictionary is protocol *data* that WhatsApp ships inside every
client (the same list is present in whatsmeow, Baileys, libsignal...).  It is
committed to this repository so the bot needs no downloads at runtime.

Usage:
    python3 tools/gen_tokens.py /path/to/Baileys/src/WABinary/constants.ts
"""

from __future__ import annotations

import re
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "xbot", "wa", "tokens.py")

STRING_RE = re.compile(r"'((?:\\.|[^'\\])*)'", re.S)


def js_string_to_py(raw: str) -> str:
    raw = raw.replace("\\'", "'").replace('\\"', '"')
    raw = raw.replace("\\n", "\n").replace("\\t", "\t").replace("\\\\", "\\")
    return raw


def extract_strings(text: str) -> list:
    return [js_string_to_py(m.group(1)) for m in STRING_RE.finditer(text)]


def slice_between(text: str, start_marker: str, end_marker: str) -> str:
    start = text.index(start_marker)
    end = text.index(end_marker, start)
    return text[start:end]


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    src = open(sys.argv[1], encoding="utf-8").read()

    # ---- TAGS -----------------------------------------------------------
    tags_block = slice_between(src, "export const TAGS", "\n}")
    tags = {k: int(v) for k, v in re.findall(r"(\w+)\s*:\s*(\d+)", tags_block)}

    # ---- DOUBLE_BYTE_TOKENS --------------------------------------------
    dbl_block = slice_between(src, "export const DOUBLE_BYTE_TOKENS", "export const SINGLE_BYTE_TOKENS")
    dbl_dicts = []
    for chunk in re.findall(r"\[(.*?)\n\t\]", dbl_block, re.S):
        dbl_dicts.append(extract_strings(chunk))
    if not dbl_dicts:
        raise SystemExit("could not parse DOUBLE_BYTE_TOKENS")

    # ---- SINGLE_BYTE_TOKENS --------------------------------------------
    sgl_block = slice_between(src, "export const SINGLE_BYTE_TOKENS", "export const TOKEN_MAP")
    sgl = extract_strings(sgl_block)

    lines = [
        '"""WhatsApp binary protocol token dictionary (data tables only).',
        "",
        "Generated by ``tools/gen_tokens.py`` from the publicly documented token",
        "list also shipped by Baileys / whatsmeow.  Do not edit by hand.",
        '"""',
        "",
        f"TAGS = {tags!r}",
        "",
        f"SINGLE_BYTE_TOKENS = {sgl!r}",
        "",
        "DOUBLE_BYTE_TOKENS = [",
    ]
    for d in dbl_dicts:
        lines.append(f"    {d!r},")
    lines.append("]")
    lines += [
        "",
        "TOKEN_MAP = {}",
        "for _i, _tok in enumerate(SINGLE_BYTE_TOKENS):",
        "    TOKEN_MAP[_tok] = (None, _i)",
        "for _d, _dict in enumerate(DOUBLE_BYTE_TOKENS):",
        "    for _j, _tok in enumerate(_dict):",
        "        TOKEN_MAP[_tok] = (_d, _j)",
        "",
    ]
    out = os.path.normpath(OUT)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {out}: {len(sgl)} single-byte, {len(dbl_dicts)} double-byte dictionaries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
